### ISSUE TITLE
Unable to join server, nullpointerexception

### ISSUE THREAD

**Issue by Alkiasan** [TheIllusiveC4/CorpseComplex#42] opened 2020-07-03 17:52 UTC
#### Versions (Be specific, do not write "latest"):
* Corpse Complex: 1.14.4-2.0-beta5
* Forge: 28.2.0
#### Observed Behavior: 
Upon joining, after "encrypting..." the player is disconnected. Server logs don't say anything. latest.log seems to be relating to corpsecomplex. Interestingly, I was able to connect to the server once, but after reconnecting, i am no longer able to connect. Singleplayer works fine, tried refreshing corpsecomplex configs serverside, but that didn't work.
#### Expected Behavior:
player can join normally.
#### Steps to Reproduce:
1. Start MC
2. Join server
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).
https://pastebin.com/n9n0kNg5

**Comment by Alkiasan** [comment] 2020-07-03 18:10
Update: Seems to be a conflict between Bountiful, Kottle, and CorpseComplex. Updating title...

**Comment by Alkiasan** [comment] 2020-07-03 18:15
Update 2: Nevermind, Issue returned again.

**Comment by TheIllusiveC4** [comment] 2020-07-03 19:14
Duplicate of https://github.com/TheIllusiveC4/CorpseComplex/issues/41
I just needed to backport the fix to 1.14.4

**Closed as completed by TheIllusiveC4** 2020-07-03 19:14 UTC
Labels: bug
