### ISSUE TITLE
Loss of all items and gear upon death.

### ISSUE THREAD

**Issue by Punkwashed** [TheIllusiveC4/CorpseComplex#39] opened 2020-06-11 22:51 UTC
Was inside of my house during the Rat moon event, ended up getting surrounded so I backed up towards my wooden door, forgot there were spikes on the other side so i cornered myself. ended up dying by a Brute Zombie in the corner, spawned in my bed about 10 blocks away and had lost everything in my inventory, hotbar, and my backpack disappeared. including what was in my hotbar, baubles stayed and anything in my belt stayed.
Was using a gladiolus and an iron pickaxe, had a backpack on and no other armor

I play on the modpack Rebirth of Night. version 2.77.5
Corpse Complex version 1.0.10.1

#### Steps to Reproduce:
1.rat moon event.
2. die by a brute zombie

From my tests, No matter what gear or what world im in, if i die by a zombie brute, i lose all of my gear, and armor.

**Comment by TheIllusiveC4** [comment] 2020-06-12 03:11
Please provide version details for Corpse Complex and Forge and your configuration settings.

**Comment by Punkwashed** [comment] 2020-06-12 18:56
Added the version, Where do i find forge and configuration?

**Comment by TheIllusiveC4** [comment] 2020-06-12 19:31
Your Forge version is whatever Forge version you installed. You can see it in the bottom left of your title screen if you have Forge installed. The configuration file is located in your instance's `config` folder as `corpsecomplex.cfg`.

**Comment by Punkwashed** [comment] 2020-06-12 22:10
Im not very knowledgeable with this stuff so sorry for the ignorance, I think since there is a custom main-screen with the modpack it doesn't show it, but from the mod list it says forge mod loader 8.0.99.99 and minecraft forge 14.23.5.2847

Here is the entire config file.
# Configuration file

##########################################################################################################
# effects
#--------------------------------------------------------------------------------------------------------#
# Add potions effects that will be applied to players on respawn
##########################################################################################################

effects {
    # Set to true to enable effects module
    B:"Enable Effects Module"=false

    # List of effects to apply to players on respawn that can be cured by the curing items list
    # Format: [effect] [duration(secs)] [power]
    S:"Curable Respawn Effects" <
     >

    # List of items that will be used by 'Curable Respawn Effects'
    S:"Curative Items" <
        minecraft:milk_bucket
     >

    # List of effects to apply to player on respawn
    # Format: [effect] [duration(secs)] [power]
    S:"Uncurable Respawn Effects" <
     >

    ##########################################################################################################
    # custom respawn effect
    #--------------------------------------------------------------------------------------------------------#
    # Customize your own respawn effect for modifying player attributes
    ##########################################################################################################

    "custom respawn effect" {
        # Set to true to enable custom effect applied on respawn
        B:"Enable Custom Respawn Effect"=false

        # Set duration (seconds) for the effect
        I:Duration=0

        # List of items that can cure the effect
        S:"Curative Items" <
            minecraft:milk_bucket
         >

        # Set to true to enable gradual recovery (modifiers will diminish gradually as the effect goes on)
        B:"Gradual Recovery"=false

        # Set maximum health modifier
        D:"Maximum Health Modifier"=0.0

        # Set armor modifier
        D:"Armor Modifier"=0.0

        # Set armor toughness modifier
        D:"Armor Toughness Modifier"=0.0

        # Set attack damage modifier
        D:"Attack Damage Modifier"=0.0

        # Set attack speed percent modifier
        D:"Attack Speed Percent Modifier"=0.0

        # Set movement speed percent modifier
        D:"Movement Speed Percent Modifier"=0.0

        # Set to true to disable eating food while effect is active
        B:"Cannot Eat Food"=false

        # Set to true to disable gaining experience while effect is active
        B:"Cannot Gain XP"=false
    }

}


##########################################################################################################
# experience
#--------------------------------------------------------------------------------------------------------#
# Customize experience loss on death
##########################################################################################################

experience {
    # Set to true to enable experience module
    B:"Enable Experience Module"=true

    # Set to true to keep all XP on death
    B:"Keep All XP"=false

    # Percent of experience lost on death
    D:"Lost XP Percent"=1.0

    # Maximum amount of experience that can be recovered, 0 to disable
    I:"Maximum Recoverable XP"=0

    # Percent of lost experience that can be recovered
    D:"Recoverable XP Percent"=0.25
}


##########################################################################################################
# hunger
#--------------------------------------------------------------------------------------------------------#
# Customize hunger and saturation values on respawn
##########################################################################################################

hunger {
    # Set to true to enable hunger module
    B:"Enable Hunger Module"=true

    # Set to true to retain food level on death
    B:"Keep Food Level"=true

    # Highest amount of food level you can respawn with
    I:"Maximum Food Level"=14

    # Lowest amount of food level you can respawn with
    I:"Minimum Food Level"=3

    # Set to true to retain saturation on death
    B:"Keep Saturation"=false
}


##########################################################################################################
# inventory
#--------------------------------------------------------------------------------------------------------#
# Customize how your inventory is handled on death and respawn
##########################################################################################################

inventory {
    # Set to true to enable inventory module
    B:"Enable Inventory Module"=true

    # Set to true to keep equipped armor on death
    B:"Keep Armor"=true

    # Set to true to keep non-mainhand hotbar items on death
    B:"Keep Hotbar"=true

    # Set to true to keep mainhand item on death
    B:"Keep Mainhand"=true

    # Set to true to keep offhand item on death
    B:"Keep Offhand"=true

    # Set to true to keep main inventory (non-equipped non-hotbar) items on death
    B:"Keep Main Inventory"=false

    # Percent of durability lost on death for drops
    D:"Durability Loss on Drops"=0.15

    # Percent of durability lost on death for kept items
    D:"Durability Loss on Kept Items"=0.15

    # Percent of energy drained on death for drops
    D:"Energy Drain on Drops"=0.15

    # Percent of energy drained on death for kept items
    D:"Energy Drain on Kept Items"=0.15

    # Percent chance that items that are kept will still drop
    D:"Random Drop Chance"=0.0

    # Set to true to only apply random drop chance to the main inventory
    B:"Random Drop Only Main Inventory"=false

    # Percent chance that dropped items will be destroyed
    D:"Random Destroy Chance"=0.0

    # List of items that are always kept
    S:"Essential Items" <
     >

    # List of items that are always dropped
    S:"Cursed Items" <
     >

    # Set to true to destroy cursed items instead of dropping them
    B:"Destroy Cursed Items"=false

    # Time (in seconds) to set for drop despawn timer, -1 for vanilla
    I:"Drop Despawn Timer"=-1

    # Set to true to keep Baubles on death
    B:"Keep Baubles"=true

    # Set to true to keep Cosmetic Armor on death
    B:"Keep Cosmetic Armor"=false

    # Set to true to keep Toolbelt on death
    B:"Keep Toolbelt"=true
    B:"Keep Wearable Backpack"=true

    # Set to true to limit durability loss so that items will never break due to death penalities
    B:"Limit Durability Loss"=true

    # Set to true to prevent death drops from despawning
    B:"No Drop Despawn"=false

    ##########################################################################################################
    # soulbinding
    #--------------------------------------------------------------------------------------------------------#
    # Enable and customize the soulbinding enchantment
    ##########################################################################################################

    soulbinding {
        # Set to true to enable Soulbinding enchantment
        B:"Enable Soulbinding Enchantment"=false

        # The max level of the enchantment
        I:"Max Level"=4

        # The percent chance that the item will drop a level in the enchantment on death when kept
        D:"Chance to Drop Level on Saved Item"=1.0

        # The base percent chance that the enchantment will save an item on death regardless of level
        D:"Base Save Probability"=0.25

        # The percent chance increase that each level in the enchantment will give to saving an item on death
        D:"Extra Save Probability per Level"=0.25

        # Set to true to allow enchanting Soulbinding at the enchantment table
        B:"Can Apply at Enchanting Table"=true

        # Set to true to allow enchanting Soulbinding on books
        B:"Allowed on Books"=true

        # The rarity of the enchantment (COMMON, UNCOMMON, RARE, or VERY_RARE)
        S:Rarity=RARE
    }

}


##########################################################################################################
# respawning
#--------------------------------------------------------------------------------------------------------#
# Customize general respawning rules
##########################################################################################################

respawning {
    # Set to true to enable respawning module features
    B:"Enable Respawning Module"=true

    # Set to true to disable beds setting spawn points
    B:"Disable Bed Spawn Points"=false

    # If Return Scroll is true, set to true to automatically give players a return scroll on respawn
    B:"Give Scroll on Respawn"=false

    # A list of items to give players on respawn. The format is modid:item_name;stacksize;metadata.
    S:"Respawn Items" <
     >

    # Set to true to enable a craftable return scroll that teleports players to their death location
    B:"Return Scroll"=true

    # Mobs to spawn at location on death
    S:"Spawn Mobs on Death" <
     >
}

**Comment by Punkwashed** [comment] 2020-06-14 22:37
Further tests have told me that only Zombie Brutes using tools will delete my inventory, it does not happen if the zombie brute has no tool.

**Comment by TheIllusiveC4** [comment] 2020-06-14 23:28
Does it happen with any other mob, as far as you're aware?

In addition, do the logs show any error messages when your inventory gets deleted? If you don't know where those are, they're in the `logs` folder. You can also see the log while the game is open, but the way to do this will depend on your specific method of running Minecraft.

**Comment by Punkwashed** [comment] 2020-06-14 23:47
Something happened that said i died by magic, and i lost all my items including baubles, but i am unsure of what happened then. from any tests ive done the brute zombie has been the only thing to delete my inventory. the bug is a bit inconsistent.

I did not see anything on the logs.

**Comment by TheIllusiveC4** [comment] 2020-06-14 23:56
How are you performing your tests? I ask because I'm not familiar with the modpack enough to know how to summon/encounter Brute Zombies, but I'll need to replicate this behavior for myself before I can figure out a solution.

**Comment by Punkwashed** [comment] 2020-06-15 00:00
i use the command /summon specialmobs:brutezombie after putting some gear in my inventory then die to it. i can make a new game and immediately cause the bug

**Comment by TheIllusiveC4** [comment] 2020-06-15 02:07
Can you describe what gear you put on or describe the steps to reproduce the bug in more detail? I've downloaded the modpack and tested this many times, I never lose my inventory when I die to a Brute Zombie holding a tool.

**Comment by Punkwashed** [comment] 2020-06-15 02:10
hmm. there is honestly nothing more i do, the gear i use is random and never consistent. it happens more commonly when i die right after spawning the mob. if it doesnt work i kill the mob and spawn another one.

Sorry I miss-clicked the close button.

**Comment by Punkwashed** [comment] 2020-06-15 02:47
https://www.youtube.com/watch?v=f1P2B2r0SEg&feature=youtu.be

for proof of that I am actually having this issue

**Comment by TheIllusiveC4** [comment] 2020-06-15 03:35
Thanks for providing a video of the issue. Unfortunately, it does seem like we're doing similar things but with different results. Quite odd. I'm not sure if I can provide a solution, but I'll try to do some more testing on my end.

**Comment by Punkwashed** [comment] 2020-06-15 03:58
thank you for your assistance.

**Comment by TheIllusiveC4** [comment] 2020-06-15 07:27
I'm going to close this so that all discussion and updates can be condensed to https://github.com/TheIllusiveC4/CorpseComplex/issues/40 which is pretty much about the same issue.

**Closed as completed by TheIllusiveC4** 2020-06-15 07:27 UTC
Labels: bug
