### ISSUE TITLE
[1.15.2] Crash - Curios Integration 

### ISSUE THREAD

**Issue by Intezium** [TheIllusiveC4/CorpseComplex#49] opened 2020-09-30 21:38 UTC
Forge-31.2.41
CorpseComplex-2.0-beta-9
Curios-2.0.2.6
[crash.txt](https://github.com/TheIllusiveC4/CorpseComplex/files/5308367/crash-2020-10-01_00.31.24-server.txt)

**Comment by TheIllusiveC4** [comment] 2020-10-04 04:58
Duplicate of https://github.com/TheIllusiveC4/CorpseComplex/issues/46

**Closed as completed by TheIllusiveC4** 2020-10-04 04:58 UTC
Labels: bug, duplicate
